### ISSUE TITLE
should we remove the setTwitter step in 5 steps?

### ISSUE THREAD

**Issue by PirateCode-eth** [ForeverPFP/primary-pfp-frontend#26]
if a user want to be connected, he can set twitter username to his primary ENS, so looks like set twitter content can be removed from the steps? 

but we can still fetch the twitter content set in primary ENS to make people easier to follow community twitter accounts.

I think the less step we make it in homepage, the more users will join in the end, what do you think? @0xtiby

**Comment by PirateCode-eth** [comment]
if ok, you can merge this, if not, just close it :)
https://github.com/ForeverPFP/primary-pfp-frontend/pull/27

**Comment by 0xtiby** [comment]
Hum I like the idea of people setting their twitter account. Because it's one step more on adding more infos on their eID. 
I think a solutions could be just shhow step 1 to 3 first. And only show 4 and 5 when user did the three previous. 

This way we can keep the basics simple with only 3 steps and let people do more if they want after 

What do you think ?

**Comment by PirateCode-eth** [comment]
Yes, good idea. 100%

**Comment by 0xtiby** [comment]
Fix by #28
